@startuml diagram_add_recipe
title C – Neues Rezept hinzufügen (f_add_recipe)

start
:Name eingeben\n(f_input_recipe_name);
if (Name ok?) then (ja)
  :Zutaten eingeben\n(f_input_ingredients);
  :Zubereitung eingeben\n(f_input_recipe_instruction);
  :Validieren\n(f_validate_ingredients_list);
  if (Zutaten ok?) then (ja)
    :in all_recipes speichern\nall_recipes[name] = {\n  'zutaten': ingredients_list,\n  'zubereitung': instruction\n};
    :Erfolgsmeldung;
    :optional: f_save_recipes(all_recipes)?;
  else
    :Fehlermeldung;
  endif
else
  :Fehlermeldung (Name);
endif
stop
@enduml